### ISSUE TITLE
Not really an issue, but i found no other way to contact you

### ISSUE THREAD

**Issue by dagnyforhust** [vprusso/youtube_tutorials#2]
I really didn't understand because there was a part in your video where you attempted to print(buyers) however it printed the elements, not the exact element. Later in the video you printed it as buyers[i].text and the program stopped printing elements. Could you please explain to me how .text stops the program from printing elements, and also how to print something without printing any elements, without using a for loop like in the video. Thanks in advance

**Comment by vprusso** [comment]
Hi Dagnyforhust. In the "About" section of my channel, I list my contact. Also, for the relevant video, there is a comment section. It's hard for me to know what you are referring to from this as this doesn't appear to be specific to any file or video. I would suggest you comment on the relevant video so that it may help others who have a similar question.
